### ISSUE TITLE
Improve Rummy AI opponent decision making

### ISSUE THREAD

**Issue by OrderAndCh4oS** [sarcoma/Python-Rummy#10]
Currently, the AI opponent checks to see if picking up the discard will result in a lower score or not, if it does it will pick up the discard. A lower score isn't the only determining factor of whether or not to pick up a discard; a player could also pick up the discard if it increases their chances of making melds later on. The AI could see if picking the card up will improve its odds of making melds. 

The odds could be determined by past discards and the cards other players pick up.

How the AI chooses a discard is currently not optimal. At the moment the AI will throw away whichever card gives it the lowest scoring hand. It will throw away cards that form partial melds. The AI should check whether the card it's throwing away belongs to a partial meld and throw away a card that is less useful.

**Comment by chandrakanth527** [comment]
I think hardcoding the rules would take a lot of time and it would get very very complicated. What i was thinking to use some machine learning model. Do you want to go this route?

**Comment by OrderAndCh4oS** [comment]
@chandrakanth527  Absolutely, it was one of the motivations for starting the project in the first place. 

The last set of changes I made were an attempt to make it easier to extract data from games. 

If you'd like to pick up the baton and try to move it forward that would be fantastic. 

I've lacked the knowledge and the time to gain it. But will offer any support I can in helping you get set up and will merge in anything you're able to get working.

**Comment by chandrakanth527** [comment]
actually a lot of functions you wrote are really valuable. so thats a good start

**Comment by OrderAndCh4oS** [comment]
@chandrakanth527 That's good to hear, so is this something you'd like to work on? It'd be really exciting to see what you'd be able to do along those lines. 

There is also: https://github.com/sarcoma/Python-Rummy/issues/16 which has some rough ideas for data to extract.
