### ISSUE TITLE
Review potential security vulnerabilities in your dependencies via Denpendabot PRs

### ISSUE THREAD

**Issue by OrderAndCh4oS** [sarcoma/Python-Rummy#20]
Look at updating any outdated dependencies and updating the requirements.txt to suit.

Dependabot has created some PRs that need to be reviewed.

**Comment by saisiddhant12** [comment]
@sarcoma 
is it about creating a requirement file ?

**Comment by OrderAndCh4oS** [comment]
I should have closed this. It's now using Poetry. Though if you want to check that it's dependencies are up to date still please do. Happy to accept any PRs.
