### ISSUE TITLE
Write more tests

### ISSUE THREAD

**Issue by OrderAndCh4oS** [sarcoma/Python-Rummy#4]
The coverage so far is for the scoring system. It'd be great to get some more test coverage in other areas. 

If anyone is interested in writing some tests, please do.

**Comment by zbendas** [comment]
Hi! I'm interested in giving some test writing a shot. I've gone ahead and forked the repo and started some work. Anything I should keep in mind or look out for while tinkering? I'm new to open source, but came here from your post over on dev.to!

**Comment by OrderAndCh4oS** [comment]
Hey, thanks so much, nice to meet you. 

Start with stuff that you can easily understand, then just make sure that when you enter the data the method spits out the desired result. Don't overthink it, keep it simple. 

Some parts like the players turns and inputs will be a pain to test, so if there is a method that expects user input leave it be for now. These need to be broken up at some point to make them more testable. If you have any ideas how I can separate the view layers, I'm all ears on that too. 

If you think you see anything that can be improved (believe me it can all be improved), please let me know I'm open to all suggestions.
