### ISSUE TITLE
command_line.py file no longer required

### ISSUE THREAD

**Issue by OrderAndCh4oS** [sarcoma/Python-Rummy#6]
There is no longer any need for the `command_line.py` it's contents can be moved to the `__main__.py` which currently imports it. 

The `setup.py` file will need to be updated to use the  `__main__.py` file afterwards.

**Comment by hardianlawi** [comment]
I'll take a look into it

**Comment by OrderAndCh4oS** [comment]
@hardianlawi Great thanks.
